#!/usr/bin/env python

import argparse

from PyModEM import ModEMData


description = '''Read a'''

parser = argparse.ArgumentParser(description=description)
parser.add_argument('data_file', help='Filepath to the data file', type=str)
parser.add_argument('-s', '--save',
                    help='Rewrite the data file as filename',
                    type=str,
                    default=None,
                    )

args = parser.parse_args()


data_filename = args.data_file
save = args.save

data_file = ModEMData.ModEMData(data_filename)

print("Number of stations: ", data_file.nstations)
print("Number of periods: ", data_file.nperiods)
print("Number of data types: ", data_file.ndata_types)
print("Number of compoments: ", data_file.ncomponents, data_file.components)

if save is not None:
    print("Re-writing datafile as: ", save)
    data_file.write_data(save)
