function h0 = CondPlotSet(Cond,grid,options)
% Usage CondPlotSet(Cond,grid,options)
%
%  plots conductivity; grid is a structure containing dx,dy,dz
%   options gives initial plot options

[Nx,Ny,Nz] = size(Cond);
h0 = figure('Position',[100,100,600,600],...
	'PaperPosition',[1,1,6,6],...
	'PaperOrientation','Landscape',...
    'Color','white');
axRect = [.1,.1,.85,.8];
padding = 0;
cblabel = 'log_{10} \sigma';
cmap = jet;
proj = 'miller'; %lambert;
label = 1;
flip = 0;
latlon = 0;
plotmap = 0;
temp = ones(Nx+1,Ny+1,Nz+1);
temp(1:Nx,1:Ny,1:Nz) = Cond;
limU = max(max(max(Cond)));
limL = min(min(min(Cond)));
if limL==limU
    limL = limL - 0.1;
    limU = limU + 0.1;
end
Clims = [limL,limU];

if nargin < 3
    Np = 1;
    Slice = 'Z';
    i1 = 1;
    i2 = Nx + 1;
    j1 = 1;
    j2 = Ny + 1;
    k1 = 1;
    k2 = Nz + 1;
else
    Np = options.Np;
    Slice = options.slice;
    i1 = options.iXlim(1);
    i2 = options.iXlim(2);
    j1 = options.iYlim(1);
    j2 = options.iYlim(2);
    k1 = options.iZlim(1);
    k2 = options.iZlim(2);
    if isfield(options,'padding')
        padding = options.padding;
    end
    if isfield(options,'cblabel')
        cblabel = options.cblabel;
    end
    if isfield(options,'cmap')
        cmap = options.cmap;
    end
    if isfield(options,'clims')
        Clims = options.clims;
    end
    if isfield(options,'flipud')
        flip = options.flipud;
    end
    if isfield(options,'latlon')
        latlon = options.latlon;
    end
    if isfield(options,'plotmap')
        plotmap = options.plotmap;
    end
end

if flip
    cmap = flipud(cmap);
end

h1 = axes('Position',axRect);
if isa(grid,'llgrid')
    x = grid.lat(1)+[0 ; cumsum(grid.dlat)];
    y = grid.lon(1)+[0 ; cumsum(grid.dlon)];
    z = grid.depth(1)+[0 ; cumsum(grid.dz)];
else
    x = grid.origin(1)+[0 ; cumsum(grid.dx)];
    y = grid.origin(2)+[0 ; cumsum(grid.dy)];
    z = grid.origin(3)+[0 ; cumsum(grid.dz)];
end
%units = 'm';
%if isfield(grid,'units')
%    units = grid.units;
%end
units = grid.units;
i1 = i1 + padding;
i2 = i2 - padding;
j1 = j1 + padding;
j2 = j2 - padding;
P = struct('Cond',temp,'X',x,'Y',y,'Z',z,'units',units,'ax',h1,...
	'Slice',Slice,'Np',Np,'i1',i1,'i2',i2,'j1'...
	,j1,'j2',j2,'k1',k1,'k2',k2,'Clims',Clims,'nointerp',1,'flipud',flip,...
    'padding',padding,'PlotType','Con',...
    'PlotSites',0,'SiteX',[],'SiteY',[],...
    'PlotLatLon',plotmap,'latlon',latlon,'lat0',0.0,'lon0',0.0,'proj',proj,...
    'PlotColorBar',1,'Label',label,'cblabel',cblabel,'cmap',cmap);
set(h0,'UserData',P)

if(Slice == 'Z')
  C = P.Cond(i1:i2,j1:j2,Np);
  xLab = 'Y';
  yLab = 'X';
  X =  y(j1:j2);
  Y = x(i1:i2);
  lev = z;
  Nslice = Nz;
  AxMode = 'xy'
elseif (Slice == 'X')
  C = squeeze(P.Cond(Np,j1:j2,k1:k2)).';
  xLab = 'Y';
  yLab = 'Z';
  X =  y(j1:j2);
  Y = z(k1:k2);
  lev = x;
  Nslice = Nx;
  AxMode = 'ij'
elseif(Slice == 'Y')
  C = squeeze(P.Cond(i1:i2,Np,k1:k2)).';
  xLab = 'X';
  yLab = 'Z';
  X =  x(i1:i2);
  Y = z(k1:k2);
  lev = y;
  Nslice = Ny;
  AxMode = 'ij'
else
  %  write error msg, return
end

pcolor(X,Y,C);caxis(Clims);colormap(cmap);
set(gca,'FontWeight','demi','FontSize',14)
xlabel(xLab)
ylabel(yLab)
axis(AxMode)
hold on
if P.PlotSites
    plot(P.SiteY,P.SiteX,'k^','MarkerSize',10,'LineWidth',2);
end
hold off

cb = colorbar('FontSize',14);
title(cb,P.cblabel,'FontWeight','demi','FontSize',14);

for k = 1:Nslice
   Slices{k} = [ num2str(k) ' : ' num2str(lev(k),'%8.4e')] ;
end

uicontrol('Units','normalized',...
	'FontWeight','demi',...
	'Position',[.075,.95,.05,.030],...
    'BackgroundColor','white',...
	'String','-',...
	'Tag','Slice -',...
	'Style','pushbutton',...
	'CallBack','CondPlotCB')
uicontrol('Units','normalized',...
	'FontWeight','demi',...
	'Position',[.125,.95,.05,.030],...
    'BackgroundColor','white',...
	'String','+',...
	'Tag','Slice +',...
	'Style','pushbutton',...
	'CallBack','CondPlotCB')
uicontrol('Units','normalized',...
	'FontWeight','demi',...
	'Position',[.175,.95,.20,.030],...
    'BackgroundColor','white',...
	'String',Slices,...
	'Tag','Plot Slice',...
	'Style','popupmenu',...
	'CallBack','CondPlotCB',...
	'Value',Np);
uicontrol('Units','normalized',...
	'FontWeight','demi',...
	'Position',[.375,.95,.10,.03],...
    'BackgroundColor','white',...
	'String','X',...
	'Tag','X Slice',...
	'Style','radiobutton',...
	'CallBack','CondPlotCB',...
	'Value',0);
uicontrol('Units','normalized',...
	'FontWeight','demi',...
	'Position',[.475,.95,.10,.03],...
    'BackgroundColor','white',...
	'String','Y',...
	'Tag','Y Slice',...
	'Style','radiobutton',...
	'CallBack','CondPlotCB',...
	'Value',0);
uicontrol('Units','normalized',...
	'FontWeight','demi',...
	'Position',[.575,.95,.10,.03],...
    'BackgroundColor','white',...
	'String','Z',...
	'Tag','Z Slice',...
	'Style','radiobutton',...
	'CallBack','CondPlotCB',...
	'Value',1);
uicontrol('Units','normalized',...
	'FontWeight','demi',...
	'Position',[.675,.95,.10,.03],...
    'BackgroundColor','white',...
	'String','Limits',...
	'Tag','Limits',...
	'Style','pushbutton',...
	'CallBack','CondPlotCB',...
	'Value',1);
uicontrol('Units','normalized',...
	'FontWeight','demi',...
	'Position',[.775,.95,.10,.03],...
    'BackgroundColor','white',...
	'String','Data',...
	'Tag','Data',...
	'Style','pushbutton',...
	'CallBack','CondPlotCB',...
	'Value',1);