function varargout = ModEM_GUI(action)
% ModEM_GUI - A Graphical User Interface for using ModEM.
%
%  --------------------
%  Bo Yang, 2013.
%  Institute of Geophysics and Geomatics,
%  China University of Geosciences, Wuhan, China.
%  College of Earth, Ocean, and Atomspheric Sciences,
%  Oregon State University, Corvallis, USA.
%  Comments, bug reports and questions, please send to:
%  yangbo@cug.edu.cn or yang@coas.oregonstate.edu.
%  Copyright 2013-2017 Bo Yang, IGG, CUG.
%  $Revision: 1.0 $ $Date: 2013/10/28 $
%  Last change: 2013/11/08 09:10:36.

%  Revision log:
%  2013/10/28 : Created.

	if nargin < 1
		action = 'initialize';
	end % nargin.

	switch action
	case 'initialize'
		% define the btn size in the main GUI.
		btnr = 5;       % number of btn rows.
		btnw = 0.98;    % btn width.
		btnh = 1/btnr;  % btn height.
		hMainFig = figure(... % the main GUI figure.
		                  'ToolBar','none',...
		                  'MenuBar','none',...
		                  'HandleVisibility','callback',...
		                  'Name','ModEM-GUI',...
		                  'NumberTitle','off',...
		                  'Units','Normalized',...
		                  'tag','tMainFig',...
		                  'Position',[0.01,0.45,0.16,0.5],...
		                  'Color', get(0, 'defaultuicontrolbackgroundcolor'));
		callbackCmd = 'close gcf;ModEM_GUI(''mve2dmodel'')';
		hBtnMk2DModel = uicontrol(... % button for making 2d model.
		                  'Parent',hMainFig,...
		                  'Units','Normalized',...
		                  'HandleVisibility','callback',...
		                  'Position',[0.01,1-btnh*1,btnw,btnh],...
		                  'FontSize',10,...
		                  'tag','tBtnMk2DModel',...
		                  'Enable','on',...
		                  'String','Make, View, Edit 2D Model',...
		                  'Callback',callbackCmd);
		callbackCmd = 'close gcf;ModEM_GUI(''mve3dmodel'')';
		hBtnMk3DModel = uicontrol(... % button for making 3d model.
		                  'Parent',hMainFig,...
		                  'Units','Normalized',...
		                  'HandleVisibility','callback',...
		                  'Position',[0.01,1-btnh*2,btnw,btnh],...
		                  'FontSize',10,...
		                  'tag','tBtnMk3DModel',...
		                  'Enable','on',...
		                  'String','Make, View, Edit 3D Model',...
		                  'Callback',callbackCmd);
		callbackCmd = 'close gcf;ModEM_GUI(''makedata'')';
		hBtnMkData = uicontrol(... % button for making data file.
		                  'Parent',hMainFig,...
		                  'Units','Normalized',...
		                  'HandleVisibility','callback',...
		                  'Position',[0.01,1-btnh*3,btnw,btnh],...
		                  'FontSize',10,...
		                  'tag','tBtnMkData',...
		                  'Enable','on',...
		                  'String','Make, View Data File',...
		                  'Callback',callbackCmd);
		callbackCmd = 'close gcf;ModEM_GUI(''makeconv'')';
		hBtnMkConv = uicontrol(... % button for making convariance file.
		                  'Parent',hMainFig,...
		                  'Units','Normalized',...
		                  'HandleVisibility','callback',...
		                  'Position',[0.01,1-btnh*4,btnw,btnh],...
		                  'FontSize',10,...
		                  'tag','tBtnMkConv',...
		                  'Enable','on',...
		                  'String','Make, View, Edit Convariance File',...
		                  'Callback',callbackCmd);
		callbackCmd = 'close gcf';
		hBtnExit = uicontrol(... % button for exiting.
		                  'Parent',hMainFig,...
		                  'Units','Normalized',...
		                  'HandleVisibility','callback',...
		                  'Position',[0.01+btnw/2,0.0,btnw/2,btnh],...
		                  'FontSize',10,...
		                  'tag','tBtnExit',...
		                  'Enable','on',...
		                  'String','Exit',...
		                  'Callback',callbackCmd);
		callbackCmd = 'msgbox(''About info'',''About'')';
		hBtnAbout = uicontrol(... % button for displaying about info.
		                  'Parent',hMainFig,...
		                  'Units','Normalized',...
		                  'HandleVisibility','callback',...
		                  'Position',[0.01,0.0,btnw/2,btnh],...
		                  'FontSize',10,...
		                  'tag','tBtnAbout',...
		                  'Enable','on',...
		                  'String','About',...
		                  'Callback',callbackCmd);
	case 'mve2dmodel'
		mvemod2d();
	case 'mve3dmodel'
		mvemod3d();
	case 'makedata'
		msgbox('not implemented yet!');
	case 'makeconv'
		msgbox('not implemented yet!');
	otherwise
		error('Unsupported action!');
	end % switch action.

%
% End of the main function.
%

%----------------------------------------------------------------------%
%                          call back functions                         %
%----------------------------------------------------------------------%

