function [] = ImpPlotSet(Z,options)
% Usage ImpPlotSet(Z,options)
%
%  plots electric field components; Grid is a structure containing dx,dy,dz,
%   E a structure containg Ex, Ey Ez, and options gives initial plot options

nX = length(options.X);
nY = length(options.Y);
nPer = options.nPer;
Mplot = options.Mplot;
PlotSites = options.PlotSites;
h0 = figure('Position',[100,100,700,1000],...
	'PaperPosition',[1,1,5,8],...
	'PaperOrientation','Landscape',...
    'Color','white');
axRect1 = [.2,.50,.7,.35];
axRect2 = [.2,.1,.7,.35];
h1 = 0; h2 = 0;

%   get default plotting options from structure "options"
% Comp is E-field component to plot   
nComp = 2*(options.Comp-1) + options.Mode;
TFcomp = {'Zxx','Zxy','Zyx','Zyy','Tx','Ty'};
  
% Slice is slice to display (X, Y or Z = constant)
Slice = options.slice;
% Np = number of slice to plot initially
Np = options.Np;
% nSlice is number of slices 
nSlice = nPer;

%  i1:i2, etc. give limits x, y , z coordinates to plot
i1 = options.iXlim(1);
i2 = options.iXlim(2);
j1 = options.iYlim(1);
j2 = options.iYlim(2);
k1 = options.iZlim(1);
k2 = options.iZlim(2);

%   store all information (including data plotted) in data structure P
P = struct('Z',Z,'X',options.X,'Y',options.Y,'T',options.T,...
    'Xlim',options.Xlim,'Ylim',options.Ylim,...
	'ax1',h1,'ax2',h2,'Comp',options.Comp,'Mode',options.Mode,...
	'Slice',Slice,'Np',Np,'i1',i1,'i2',i2,'j1'...
	,j1,'j2',j2,'k1',k1,'k2',k2,'File',options.File,...
	'CLmode','Auto','CLreal',[],'CLimag',[],...
	'AmpPhase',0,'Rho',0,'nSlice',nSlice,...
	'nPer',nPer,'nX',nX,'nY',nY,...
    'SiteX',options.SiteX,'SiteY',options.SiteY,...
    'PlotType','TFs','Mplot',Mplot,'PlotSites',PlotSites);

%  now set up component to plot
[C,xLab,yLab,X,Y,AxMode,lev] = getZcomp(P);
h1 = axes('Position',axRect1);h2 = axes('Position',axRect2);
P.ax1 = h1; P.ax2 = h2;

%   associate  all of the data in structure P with figure
set(h0,'UserData',P)

plotAmpPh

for k = 1:length(lev)
   Slices{k} = [ num2str(k) ' : ' num2str(lev(k),'%6.2e')] ;
end

uicontrol('Units','normalized',...
	'FontWeight','demi',...
	'Position',[.125,.95,.05,.030],...
	'String','-',...
	'Tag','Slice -',...
	'Style','pushbutton',...
	'CallBack','ImpPlotCB')
uicontrol('Units','normalized',...
	'FontWeight','demi',...
	'Position',[.175,.95,.05,.030],...
	'String','+',...
	'Tag','Slice +',...
	'Style','pushbutton',...
	'CallBack','ImpPlotCB')
uicontrol('Units','normalized',...
	'FontWeight','demi',...
	'Position',[.225,.95,.20,.030],...
	'String',Slices,...
	'Tag','Plot Slice',...
	'Style','popupmenu',...
	'CallBack','ImpPlotCB',...
	'Value',Np);
uicontrol('Units','normalized',...
	'FontWeight','demi',...
	'Position',[.425,.95,.10,.03],...
	'String','X',...
	'Tag','X Slice',...
	'Style','radiobutton',...
	'CallBack','ImpPlotCB',...
	'Value',0);
uicontrol('Units','normalized',...
	'FontWeight','demi',...
	'Position',[.525,.95,.10,.03],...
	'String','Y',...
	'Tag','Y Slice',...
	'Style','radiobutton',...
	'CallBack','ImpPlotCB',...
	'Value',0);
uicontrol('Units','normalized',...
	'FontWeight','demi',...
	'Position',[.625,.95,.10,.03],...
	'String','T',...
	'Tag','T Slice',...
	'Style','radiobutton',...
	'CallBack','ImpPlotCB',...
	'Value',1);
uicontrol('Units','normalized',...
	'FontWeight','demi',...
	'Position',[.725,.95,.10,.03],...
	'String','Limits',...
	'Tag','Limits',...
	'Style','pushbutton',...
	'CallBack','ImpPlotCB')
uicontrol('Units','normalized',...
	'FontWeight','demi',...
	'Position',[.825,.95,.10,.03],...
	'String',TFcomp,...
	'Tag','Components',...
	'Style','popupmenu',...
	'CallBack','ImpPlotCB',...
	'Value',nComp);
uicontrol('Units','normalized',...
	'FontWeight','demi',...
	'Position',[.650,.91,.15,.03],...
	'String','Fix Color Scale',...
	'Tag','Fix Scale',...
	'Style','pushbutton',...
	'CallBack','ImpPlotCB',...
	'Value',1);
uicontrol('Units','normalized',...
	'FontWeight','demi',...
	'Position',[.200,.91,.14,.03],...
	'String',{'Real-Imag','Rho-Phase'},...
	'Tag','Rho-Phase',...
	'Style','popupmenu',...
	'CallBack','ImpPlotCB',...
	'Value',1);
