action = get(gcbo,'Tag');
h0 = get(gcbo,'Parent');
P = get(h0,'UserData');
switch action
case 'Slice -'
  if(P.Np > 1)
    P.Np = P.Np-1;
    set(findobj('Tag','Plot Slice','Parent',h0),'Value',P.Np);
    set(h0,'UserData',P);
    [C,xLab,yLab,X,Y,AxMode,lev] = getZcomp(P);
    h1 = P.ax1; h2 = P.ax2;
    plotAmpPh
  end
case 'Slice +'
  if(P.Np < P.nSlice)
    P.Np = P.Np+1;
    set(findobj('Tag','Plot Slice','Parent',h0),'Value',P.Np);
    set(h0,'UserData',P);
    [C,xLab,yLab,X,Y,AxMode,lev] = getZcomp(P);
    h1 = P.ax1; h2 = P.ax2;
    plotAmpPh
  end
case 'Plot Slice'
  Np = get(gcbo,'Value');
  P.Np = Np;
  set(h0,'UserData',P);
  [C,xLab,yLab,X,Y,AxMode,lev] = getZcomp(P);
  h1 = P.ax1; h2 = P.ax2;
  plotAmpPh

case 'X Slice'
  P.Slice = 'X';
  hX = gcbo;
  hP = findobj('Tag','Plot Slice','Parent',h0);
  set(findobj('Tag','Y Slice','Parent',h0),'Value',0);
  set(findobj('Tag','T Slice','Parent',h0),'Value',0);
  P.Np = min(P.Np,P.nX);
  P.i2 = min(P.i2,P.nX);
  P.j2 = min(P.j2,P.nY);
  P.k2 = min(P.k2,P.nPer);
  P.nSlice = P.nX;
  set(h0,'UserData',P)
  [C,xLab,yLab,X,Y,AxMode,lev] = getZcomp(P);
  Slices = {}
  for k = 1:P.nX
     Slices{k} = [ num2str(k) ' : ' num2str(lev(k),'%8.4e')] ;
  end
  set(hP,'Value',P.Np);
  set(hP,'String',Slices)
  h1 = P.ax1; h2 = P.ax2;
  plotAmpPh

case 'Y Slice'
  P.Slice = 'Y';
  hY = gcbo;
  hP = findobj('Tag','Plot Slice','Parent',h0);
  set(findobj('Tag','X Slice','Parent',h0),'Value',0);
  set(findobj('Tag','T Slice','Parent',h0),'Value',0);
  P.Np = min(P.Np,P.nY);
  P.i2 = min(P.i2,P.nX);
  P.j2 = min(P.j2,P.nY);
  P.k2 = min(P.k2,P.nPer);
  P.nSlice = P.nY;
  set(h0,'UserData',P)
  [C,xLab,yLab,X,Y,AxMode,lev] = getZcomp(P);
  Slices = {}
  for k = 1:P.nY
     Slices{k} = [ num2str(k) ' : ' num2str(lev(k),'%8.4e')] ;
  end
  set(hP,'Value',P.Np);
  set(hP,'String',Slices)
  h1 = P.ax1; h2 = P.ax2;
  plotAmpPh
  
case 'T Slice'
  P.Slice = 'T';
  hY = gcbo;
  hP = findobj('Tag','Plot Slice','Parent',h0);
  set(findobj('Tag','X Slice','Parent',h0),'Value',0);
  set(findobj('Tag','Y Slice','Parent',h0),'Value',0);
  P.Np = min(P.Np,P.nPer);
  P.i2 = min(P.i2,P.nX);
  P.j2 = min(P.j2,P.nY);
  P.k2 = min(P.k2,P.nPer);
  P.nSlice = P.nPer;
  set(h0,'UserData',P)
  [C,xLab,yLab,X,Y,AxMode,lev] = getZcomp(P);
  Slices = {}
  for k = 1:P.nPer
     Slices{k} = [ num2str(k) ' : ' num2str(lev(k),'%8.4e')];
  end
  set(hP,'Value',P.Np);
  set(hP,'String',Slices)
  h1 = P.ax1; h2 = P.ax2;
  plotAmpPh

case 'Limits'
  hP = gcbo;
  [C,xLab,yLab,X,Y,AxMode,lev] = getZcomp(P);
  hLimits = figure('Position',[800,800,300,150], ...
	'MenuBar','none','NumberTitle','off',...
	'Name','Set Grid Limits','UserData',h0);
  
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.1,.75,.5,.15],...
        'String',['X limits : 1-' num2str(P.nX)],...
        'Tag','X limits',...
        'Style','text')
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.55,.75,.2,.15],...
        'String',[num2str(P.i1)],...
        'Tag','X limits 1',...
        'Style','edit',...
        'CallBack','EsetLims')
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.75,.75,.2,.15],...
        'String',[num2str(P.i2)],...
        'Tag','X limits 2',...
        'Style','edit',...
        'CallBack','EsetLims')
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.1,.5,.5,.15],...
        'String',['Y limits : 1-' num2str(P.nY)],...
        'Tag','Y limits',...
        'Style','text')
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.55,.5,.2,.15],...
        'String',[num2str(P.j1)],...
        'Tag','Y limits 1',...
        'Style','edit',...
        'CallBack','EsetLims')
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.75,.5,.2,.15],...
        'String',[num2str(P.j2)],...
        'Tag','Y limits 2',...
        'Style','edit',...
        'CallBack','EsetLims')
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.1,.25,.5,.15],...
        'String',['Z limits : 1-' num2str(P.nPer)],...
        'Tag','Z limits',...
        'Style','text')
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.55,.25,.2,.15],...
        'String',[num2str(P.k1)],...
        'Tag','Z limits 1',...
        'Style','edit',...
        'CallBack','EsetLims')
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.75,.25,.2,.15],...
        'String',[num2str(P.k2)],...
        'Tag','Z limits 2',...
        'Style','edit',...
        'CallBack','EsetLims')
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.25,.05,.25,.15],...
        'String','OK',...
        'Tag','Limits OK',...
        'Style','pushbutton',...
        'CallBack','EsetLims')
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.55,.05,.25,.15],...
        'String','Reset',...
        'Tag','Reset Limits',...
        'Style','pushbutton',...
        'CallBack','EsetLims')

case 'Components'
  COMPmode = [1 1; 1 2; 2 1 ; 2 2 ; 3 1 ; 3 2 ]
  P.Comp = COMPmode(get(gcbo,'Value'),1);
  P.Mode = COMPmode(get(gcbo,'Value'),2);
  set(h0,'UserData',P);
  [C,xLab,yLab,X,Y,AxMode,lev] = getZcomp(P);
  set(findobj('Tag','Plot Slice','Parent',h0),'Value',P.Np);
  h1 = P.ax1; h2 = P.ax2;
  plotAmpPh

case 'Fix Scale'
  clReal = get(P.ax1,'CLim');
  clImag = get(P.ax2,'CLim');
  hScale = figure('Position',[700,700,300,150], ...
	'MenuBar','none','NumberTitle','off',...
	'Name','Set Color Scale','UserData',h0);
  
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.1,.75,.5,.15],...
        'String',['Real '],...
        'Tag','Real limits',...
        'Style','text')
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.55,.75,.2,.15],...
        'String',[num2str(clReal(1))],...
        'Tag','Real limits 1',...
        'Style','edit')
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.75,.75,.2,.15],...
        'String',[num2str(clReal(2))],...
        'Tag','Real limits 2',...
        'Style','edit')
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.1,.5,.5,.15],...
        'String',['Imaginary'],...
        'Tag','Imag limits',...
        'Style','text')
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.55,.5,.2,.15],...
        'String',[num2str(clImag(1))],...
        'Tag','Imag limits 1',...
        'Style','edit')
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.75,.5,.2,.15],...
        'String',[num2str(clImag(2))],...
        'Tag','Imag limits 2',...
        'Style','edit')
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.10,.05,.18,.15],...
        'String','OK',...
        'Tag','Clim OK',...
        'Style','pushbutton',...
        'CallBack','EsetLims')
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.30,.05,.18,.15],...
        'String','Auto',...
        'Tag','Auto',...
        'Style','pushbutton',...
        'CallBack','EsetLims')
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.50,.05,.18,.15],...
        'String','Load',...
        'Tag','Load CL',...
        'Style','pushbutton',...
        'CallBack','EsetLims')
  uicontrol('Units','normalized',...
        'FontWeight','demi',...
        'Position',[.70,.05,.18,.15],...
        'String','Save',...
        'Tag','Save CL',...
        'Style','pushbutton',...
        'CallBack','EsetLims')
case 'Rho-Phase'
  P.AmpPhase = get(gcbo,'Value')-1;
  P.CLmode = 'auto';
  set(h0,'UserData',P);
  [C,xLab,yLab,X,Y,AxMode,lev] = getZcomp(P);
  h1 = P.ax1; h2 = P.ax2;
  plotAmpPh
end
