%  This is a script (would take some work to make it a function, since it
%    would need access to  variables that are defined in this script, after 
%    returning control to interface.   This is very "buggy" as it has been 
%    modified from a program written ~15 years ago, for a very different 
%    application.   Not all features actually work, and this almost
%    certainly cannot be used in conjunction with other concurrently
%    running  programs in matlab.   Don't try!  See ptchEditMT_usage for
%    some instructions on use.   If things appear to hang, keep clicking
%    buttons until they unhang,
%     
%  as a script  one  needs to set variables modelFile and data File before 
%    running, e.g. 
%
%   modelFile = 'Nested_NWUSA_Z_5%_Hz_3%_run3_NLCG_027.rho';
%   dataFile = 'Z_Hz_5%_3%_22Per_final_Data_set.dat';

[allData,header,units,isign,origin,info] = readZ_3D(dataFile);
info{1}.lon(info{1}.lon<0) = info{1}.lon(info{1}.lon<0)+360;
[lat0,lon0] = latgrid.origin(info{1}.lat,info{1}.lon,info{1}.loc(:,1),...
                      info{1}.loc(:,2));
[Cond] = readCond_3D(modelFile,2); 
latmin = min(info{1}.lat);
latmax = max(info{1}.lat);
lonmin = min(info{1}.lon);
lonmax = max(info{1}.lon);
ll_lims = [lonmin,lonmax,latmin,latmax];
hLims = [-3.5,-.5];

%%  choose layer, interpolate conductivity for chosen layer onto uniform grid
obj = Cond_xy_ll(Cond,lat0,lon0);
z = [1:5:200];
obj = CONDxyz2ll(obj,'depths',z);
depth = 50;
corners(:,1,1)  = [latmin lonmin depth];

corners(:,2,1)  = [latmin lonmax depth];
corners(:,1,2)  = [latmax lonmin depth];
corners(:,2,2)  = [latmax lonmax depth];
[hz,xy,ll] = slice(obj,corners,[108,120]);

if load_hz
    load(hzFile)
end
%%   read monitor specific paramters (set in gredmon.m)
gredmon

outFile = '*.pat';
patch_names = cell(0,0);
npatch = 0;
mask_nums = [];
patch_mask = [];
patch_num = 0;
current_patch = '';
bgc = [.9,.9,1];

%   set colormap
nbath = 32;
map=jet(nbath);%map=1-map;
%map(:,1)=max(0.05,map(:,1)-0.2);
%map(:,2)=max(0.05,map(:,2)-0.1);
%map(:,3)=min(1,map(:,3)+0.2);

%  land color:  green
land_color = nbath+1;
map(land_color,:)=[0.8,0.8,0.8];
%   mask colors
next_num = land_color;
temp = bone(64);
temp=1-temp;
temp(:,1)=max(0.05,temp(:,1)-0.2);
temp(:,2)=max(0.05,temp(:,2)-0.1);
temp(:,3)=min(1,temp(:,3)+0.2);

mask_rgb = temp(1:8:60,:);
mask_rgb = [mask_rgb; temp(2:8:60,:)];
mask_rgb = [mask_rgb; temp(3:8:60,:)];
mask_rgb = [mask_rgb; temp(4:8:60,:)];
mask_rgb = [mask_rgb; temp(5:8:60,:)];
mask_rgb = [mask_rgb; temp(6:8:60,:)];
mask_rgb = [mask_rgb; temp(7:8:60,:)];
mask_rgb = [mask_rgb; temp(8:8:60,:)];

%mask_colors = [1:length(mask_rgb)]+land_color;
map = [ map ; mask_rgb ];
map(39,:) = [.9,.9,.9];

%  initialize mask
mask = zeros(size(hz));
%  set to land color where mz == 0; otherwise to 0
%mask = mask + land_color*(mz == 0);

%   set up figure
yrange = ll_lims(4)-ll_lims(3);
y0 = (ll_lims(4)+ll_lims(3))*pi/360;
xrange = (ll_lims(2) - ll_lims(1))*cos(y0);
asp = yrange/xrange;
if asp < 1
   orient = 'Landscape';
   x = width;
   y = asp*x/(1.-marg_bot);
   xpaper = 8;
   ypaper = asp*xpaper;
   rect_plt = [marg, marg*(1.-marg_bot)+marg_bot,ax,ax*(1.-marg_bot)];
else
%   for now just put everything on the bottom still
   orient = 'Portrait';
   y = height/(1.-marg_bot);
   x = y/asp;
   ypaper = 7.
   xpaper = ypaper/asp;
   rect_plt = [marg, marg*(1-marg_bot)+marg_bot,ax,ax*(1.-marg_bot)];
end
rect = [ loc x y ];
rect_paper = [1.,1.,xpaper,ypaper];
figure('Position',rect,'PaperPosition',rect_paper,'Tag','MainFigure')
% set(gcf,'MinColorMap',121);hold on
plot(info{1}.lon,info{1}.lat','k*','Markersize',10,'linewidth',2)
axes('Position',rect_plt,'Tag','GridPlotAxis')
initPltMT
colormap(map);

yn = marg_bot - .08; ys = .04; 
nbuttons = 8; space = .01;
nspace = nbuttons + 1;
xs = (ax - nspace*space)/nbuttons;
pos1 = [ -space/4 -space/4 space/2 space/2];

pos = [ marg-space/2 yn-space/2 3*(xs+space), ys+space];
uicontrol('Style','Frame',...
   	'units','normalized',...
   	'position',pos,...
      'BackgroundColor',[.4,.4,.6]);
   
pos = [ marg-space/2 yn-space/2-.07 3*(xs+space), ys+space];
uicontrol('Style','Frame',...
   	'units','normalized',...
   	'position',pos,...
		'BackgroundColor',[.4,.4,.6]);

%  Mask/Unmask
b = 1;
pos = [ marg+(b-1)*(xs+space) yn xs ys ];
uicontrol('Style','Frame',...
   	'units','normalized',...
   	'position',pos+pos1);
uicontrol('style','radiobutton', ...
        'parent',gcf, ...
        'units','normalized', ...
        'position',pos,...
        'Fontsize',guiButtonFontSize, ...
        'FontWeight','bold', ...
        'string','Mask', ...
        'Tag','Mask',...
        'Interruptible','off', ...
        'BusyAction','cancel', ...
        'callback','pedCBckMT',...
	'Value',0);

%  Mask Block
b = 2;
pos = [ marg+(b-1)*(xs+space) yn xs ys ];
uicontrol('Style','Frame',...
   	'units','normalized',...
   	'position',pos+pos1);

uicontrol('style','radiobutton', ...
        'parent',gcf, ...
        'units','normalized', ...
        'position',pos,...
        'Fontsize',guiButtonFontSize, ...
        'FontWeight','bold', ...
        'string','Mask Blk', ...
        'Tag','Mask_Blk',...
        'callback','pedCBckMT',...
	'Value',0);

%  UnMask Block
b = 3;
pos = [ marg+(b-1)*(xs+space) yn xs ys ];
uicontrol('Style','Frame',...
   	'units','normalized',...
   	'position',pos+pos1);

uicontrol('style','radiobutton', ...
        'parent',gcf, ...
        'units','normalized', ...
        'position',pos,...
        'Fontsize',guiButtonFontSize, ...
        'FontWeight','bold', ...
        'string','Unmsk Blk', ...
        'Tag','Unmsk_Blk',...
        'callback','pedCBckMT',...
	'Value',0);

%  Input Patch File
b = 4;
pos = [ marg+(b-1)*(xs+space)+3*space yn xs ys ];
uicontrol('Style','Frame',...
   	'units','normalized',...
   	'position',pos+pos1);

uicontrol('style','pushbutton', ...
        'parent',gcf, ...
        'units','normalized', ...
        'position',pos,...
        'Fontsize',guiButtonFontSize, ...
        'FontWeight','bold', ...
        'string','Read *.pat', ...
        'Tag','Read',...
        'callback','pedCBckMT',...
	'Value',0);

%  Add/Delete Patch name
b = 5;
pos = [ marg+(b-1)*(xs+space)+4*space yn-.01 xs/2 ys+.01 ];
uicontrol('Style','Frame',...
   	'units','normalized',...
   	'position',pos+pos1);

uicontrol('style','pushbutton', ...
        'parent',gcf, ...
        'units','normalized', ...
        'position',pos,...
        'Fontsize',guiButtonFontSize, ...
        'FontWeight','bold', ...
        'string','Add', ...
        'Tag','Add',...
        'callback','pedCBckMT');
     
pos = [ marg+(b-1)*(xs+space)+4*space+xs/2 yn-.01 xs/2 ys+.01 ];
uicontrol('Style','Frame',...
   	'units','normalized',...
   	'position',pos+pos1);

uicontrol('style','pushbutton', ...
        'parent',gcf, ...
        'units','normalized', ...
        'position',pos,...
        'Fontsize',guiButtonFontSize, ...
        'FontWeight','bold', ...
        'string','Del', ...
        'Tag','Del',...
        'callback','pedCBckMT');
    
b = 7.75;
pos = [ marg+(b-1)*(xs+space)+4*space yn-.01 xs ys ];
%uicontrol('Style','Frame',...
%   	'units','normalized',...
%   	'position',pos+pos1);

uicontrol('Style','text',...
   	'units','normalized',...
   	'position',pos,...
    'string','Depth',...
    'Fontsize',guiButtonFontSize, ...
        'FontWeight','bold');
    
%  Second Row 
     
yn = marg_bot - .15; ys = .04; 
nbuttons = 8; space = .01;
nspace = nbuttons + 1;
xs = (ax - nspace*space)/nbuttons;
pos1 = [ -space/4 -space/4 space/2 space/2];

%  Change Subgrid
b = 1;
pos = [ marg+(b-1)*(xs+space) yn xs ys ];
uicontrol('Style','Frame',...
   	'units','normalized',...
   	'position',pos+pos1);

uicontrol('style','radiobutton', ...
        'parent',gcf, ...
        'units','normalized', ...
        'position',pos,...
        'Fontsize',guiButtonFontSize, ...
        'FontWeight','bold', ...
        'string','Sub-grid', ...
        'Tag','Sub_grid',...
        'callback','subgrid',...
	'Value',0);

%  Restore Previous Subgrid
b = 2;
pos = [ marg+(b-1)*(xs+space) yn xs ys ];
uicontrol('Style','Frame',...
   	'units','normalized',...
   	'position',pos+pos1);

uicontrol('style','radiobutton', ...
        'parent',gcf, ...
        'units','normalized', ...
        'position',pos,...
        'Fontsize',guiButtonFontSize, ...
        'FontWeight','bold', ...
        'string','Prev Grid', ...
        'Tag','Prev_Grid',...
        'callback','pedCBckMT',...
	'Value',0);

%  Restore Full Grid
b = 3;
pos = [ marg+(b-1)*(xs+space) yn xs ys ];
uicontrol('Style','Frame',...
   	'units','normalized',...
   	'position',pos+pos1);

uicontrol('style','radiobutton', ...
        'parent',gcf, ...
        'units','normalized', ...
        'position',pos,...
        'Fontsize',guiButtonFontSize, ...
        'FontWeight','bold', ...
        'string','Full Grid', ...
        'Tag','Full_Grid',...
        'callback','pedCBckMT',...
		  'Value',0);
     
%  Output File
b = 4;
pos = [ marg+(b-1)*(xs+space)+3*space yn xs ys ];
uicontrol('Style','Frame',...
   	'units','normalized',...
   	'position',pos+pos1);

uicontrol('style','pushbutton', ...
        'parent',gcf, ...
        'units','normalized', ...
        'position',pos,...
        'Fontsize',guiButtonFontSize, ...
        'FontWeight','bold', ...
        'string','Save', ...
        'Tag','Save',...
        'callback','pedCBckMT',...
	'Value',0);

%  Add/Delete Patch name (set name here)
b = 5;
pos = [ marg+(b-1)*(xs+space)+4*space yn xs ys+.01 ];
uicontrol('Style','Frame',...
   	'units','normalized',...
   	'position',pos+pos1);

uicontrol('style','edit', ...
        'parent',gcf, ...
        'units','normalized', ...
        'position',pos,...
        'Fontsize',guiButtonFontSize, ...
        'FontWeight','bold', ...
        'string',current_patch, ...
        'Tag','patch_name',...
        'callback','current_patch = get(gcbo,''string'');');

%  listbox for selection of existing patch to edit
b = 6;
pos = [ marg+(b-1)*(xs+space)+5*space yn 1.75*xs-3*space .15 ];
uicontrol('style','listbox', ...
        'parent',gcf, ...
        'units','normalized', ...
        'position',pos,...
        'Fontsize',guiButtonFontSize, ...
        'FontWeight','bold', ...
        'string',patch_names, ...
        'Tag','ListBox',...
        'callback','setPatch',...
	     'Value',patch_num);
     
pos = [ marg+(b-1)*(xs+space)+5*space+1.80*xs-3*space yn .2*xs .15 ];
uicontrol('style','Frame', ...
   		'BackGroundColor',bgc,...
        'parent',gcf, ...
        'units','normalized', ...
        'position',pos,...
        'Tag','MC');

b = 7.75;
pos = [ marg+(b-1)*(xs+space)+4*space yn+.01 xs ys ];
%uicontrol('Style','Frame',...
%   	'units','normalized',...
%   	'position',pos+pos1);
uicontrol('Style','Frame',...
   	'units','normalized',...
   	'position',pos+pos1);

uicontrol('style','edit', ...
        'parent',gcf, ...
        'units','normalized', ...
        'position',pos,...
        'Fontsize',guiButtonFontSize, ...
        'FontWeight','bold', ...
        'string',num2str(depth), ...
        'Tag','depth',...
        'callback','pedCBckMT');
