#!/usr/bin/env python

import sys

from mtpy import MTData
from mtpy.modeling import StructuredGrid3D


if len(sys.argv) != 2:
    print("Usage: ./modem_mesh_dump mesh_file")
    sys.exit(1)

file_name = sys.argv[1]

grid = StructuredGrid3D()
grid.from_modem(file_name)

print(grid)


min_rho = grid.res_model.min()
max_rho = grid.res_model.max()

print(min_rho, max_rho)

