function varargout = mvemod2d(action,varargin)
% mvemod2d - A GUI tool for making, viewing and editing the 2D mesh model.
%
%  --------------------
%  Bo Yang, 2013.
%  Institute of Geophysics and Geomatics,
%  China University of Geosciences, Wuhan, China.
%  College of Earth, Ocean, and Atomspheric Sciences,
%  Oregon State University, Corvallis, USA.
%  Comments, bug reports and questions, please send to:
%  yangbo@cug.edu.cn or yang@coas.oregonstate.edu.
%  Copyright 2013-2017 Bo Yang, IGG, CUG.
%  $Revision: 1.0 $ $Date: 2013/10/29 $
%  Last change: 2013/11/08 12:42:15.

%  Revision log:
%  2013/10/29 : Created.

	if (nargin < 1)
		action = 'initialize';
		modelfile = '';
		modelpath = '';
	end % nargin.

	if (length(varargin) > 0)
		arg = varargin{1};
		if isstruct(arg)
			modelfile = arg.modelfile;
			modelpath = arg.modelpath;
		elseif ischar(arg)
			[modelpath,modelfile,modelext] = fileparts(arg);
			modelfile = strcat(modelfile,modelext);
		else
			error('Unsupported arguments!');
		end % isstruct.
	end % called with model file name or a model struct.

	switch action
	case 'initialize'
		% define the btn size.
		btnr = 8;      % number of btn rows.
		btnw = 0.98;   % btn width.
		btnh = 1/btnr; % btn height.
		hMvemod2dMainFig = figure(... % the main GUI figure of mvemod2d.
		                  'ToolBar','none',...
		                  'MenuBar','none',...
		                  'HandleVisibility','callback',...
		                  'Name','mvemod2d',...
		                  'NumberTitle','off',...
		                  'Units','Normalized',...
		                  'tag','tMainFig',...
		                  'Position',[0.01,0.25,0.16,0.7],...
		                  'Color', get(0, 'defaultuicontrolbackgroundcolor'));
		callbackCmd = 'mvemod2d(''open'')';
		hBtnOpenModel = uicontrol(... % button for opening the model file.
		                  'Parent',hMvemod2dMainFig,...
		                  'Units','Normalized',...
		                  'HandleVisibility','callback',...
		                  'Position',[0.01,1-btnh*1,btnw,btnh],...
		                  'FontSize',10,...
		                  'tag','tBtnOpenModel',...
		                  'Enable','on',...
		                  'String','Open Model file',...
		                  'Callback',callbackCmd);
		callbackCmd = 'mvemod3d(''new'');';
		hBtnNewModel = uicontrol(... % button for creating new the model file.
		                  'Parent',hMvemod2dMainFig,...
		                  'Units','Normalized',...
		                  'HandleVisibility','callback',...
		                  'Position',[0.01,1-btnh*2,btnw,btnh],...
		                  'FontSize',10,...
		                  'tag','tBtnNewModel',...
		                  'Enable','on',...
		                  'String','New Model file',...
		                  'Callback',callbackCmd);
		callbackCmd = 'mvemod2d(''setrange'');';
		callbackCmd = 'mvemod3d(''loadmat'');';
		hBtnLoadMat = uicontrol(... % button for loading the model struct mat file.
		                  'Parent',hMvemod2dMainFig,...
		                  'Units','Normalized',...
		                  'HandleVisibility','callback',...
		                  'Position',[0.01,1-btnh*3,btnw,btnh],...
		                  'FontSize',10,...
		                  'tag','tBtnLoadMat',...
		                  'Enable','on',...
		                  'String','Load Model mat',...
		                  'Callback',callbackCmd);
		callbackCmd = 'mvemod3d(''savemat'');';
		hBtnSaveMat = uicontrol(... % button for saving the model struct mat file.
		                  'Parent',hMvemod2dMainFig,...
		                  'Units','Normalized',...
		                  'HandleVisibility','callback',...
		                  'Position',[0.01,1-btnh*4,btnw,btnh],...
		                  'FontSize',10,...
		                  'tag','tBtnSaveMat',...
		                  'Enable','on',...
		                  'String','Save Model mat',...
		                  'Callback',callbackCmd);
		hBtnSetRange = uicontrol(... % button for setting the range of displaying.
		                  'Parent',hMvemod2dMainFig,...
		                  'Units','Normalized',...
		                  'HandleVisibility','callback',...
		                  'Position',[0.01,1-btnh*5,btnw,btnh],...
		                  'FontSize',10,...
		                  'tag','tBtnSetRange',...
		                  'Enable','on',...
		                  'String','Set Range',...
		                  'Callback',callbackCmd);
		callbackCmd = 'mvemod2d(''display'');';
		hBtnDispEdit = uicontrol(... % button for displaying and editing.
		                  'Parent',hMvemod2dMainFig,...
		                  'Units','Normalized',...
		                  'HandleVisibility','callback',...
		                  'Position',[0.01,1-btnh*6,btnw,btnh],...
		                  'FontSize',10,...
		                  'tag','tBtnDispEdit',...
		                  'Enable','on',...
		                  'String','Display & Edit',...
		                  'Callback',callbackCmd);
		callbackCmd = 'mvemod2d(''save'');';
		hBtnSave = uicontrol(... % button for saving the model file.
		                  'Parent',hMvemod2dMainFig,...
		                  'Units','Normalized',...
		                  'HandleVisibility','callback',...
		                  'Position',[0.01,1-btnh*7,btnw,btnh],...
		                  'FontSize',10,...
		                  'tag','tBtnSave',...
		                  'Enable','on',...
		                  'String','Save Model File',...
		                  'Callback',callbackCmd);
		callbackCmd = 'mvemod2d(''close'');';
		hBtnClose = uicontrol(... % button for closing.
		                  'Parent',hMvemod2dMainFig,...
		                  'Units','Normalized',...
		                  'HandleVisibility','callback',...
		                  'Position',[0.01,0,btnw,btnh],...
		                  'FontSize',10,...
		                  'tag','tBtnClose',...
		                  'Enable','on',...
		                  'String','Close',...
		                  'Callback',callbackCmd);
	case 'open'
		[modelfile,modelpath] = uigetfile({'*.rho';'*.*';},'Open a ModEM model file.');
	case 'new'
		[modelfile,modelpath] = uiputfile({'*.rho';'*.*';},'Specify the name of the new ModEM model file.');
	case 'setrange'
		msgbox('not implemented yet!');
	case 'display'
		msgbox('not implemented yet!');
	case 'callmeshtools3d'
		msgbox('not implemented yet!');
	case 'save'
		msgbox('not implemented yet!');
	case 'close'
		close all;
	otherwise
		error('Unsupported action! You must specify an action.');
	end % switch action.

%
% End of the function.
%
